# Reglas de redirección para el proxy
[[redirects]]
  # Captura cualquier petición que empiece con /api/
  from = "/api/*"
  # Y la redirige a tu backend en Render.
  # El :splat asegura que el resto de la ruta se mantenga (ej. /api/products -> /products)
  to = "https://horizon-api-yeqy.onrender.com/:splat"
  # El status 200 lo convierte en una reescritura (proxy) en lugar de una redirección 301.
  status = 200
  # Force = true asegura que esta regla se aplique incluso si hay un archivo en la ruta.
  force = true