"""Add slug and db_name to Business model for multitenancy

Revision ID: 87ad8a637cbe
Revises: 7e2d45ce3ead
Create Date: 2025-06-10 22:35:33.705934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlmodel.sql.sqltypes import AutoString


# revision identifiers, used by Alembic.
revision: str = '87ad8a637cbe'
down_revision: Union[str, None] = '7e2d45ce3ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('business', sa.Column('db_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_public_business_slug'), 'business', ['slug'], unique=True, schema='public')
    op.create_unique_constraint(None, 'business', ['db_name'], schema='public')
    op.drop_constraint(op.f('customer_business_id_fkey'), 'customer', type_='foreignkey')
    op.create_foreign_key(None, 'customer', 'business', ['business_id'], ['id'], referent_schema='public')
    op.drop_constraint(op.f('invoice_business_id_fkey'), 'invoice', type_='foreignkey')
    op.create_foreign_key(None, 'invoice', 'business', ['business_id'], ['id'], referent_schema='public')
    op.drop_constraint(op.f('payment_business_id_fkey'), 'payment', type_='foreignkey')
    op.create_foreign_key(None, 'payment', 'business', ['business_id'], ['id'], referent_schema='public')
    op.drop_constraint(op.f('product_company_id_fkey'), 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'business', ['company_id'], ['id'], referent_schema='public')
    op.drop_constraint(op.f('vendor_business_id_fkey'), 'vendor', type_='foreignkey')
    op.create_foreign_key(None, 'vendor', 'business', ['business_id'], ['id'], referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendor', type_='foreignkey')
    op.create_foreign_key(op.f('vendor_business_id_fkey'), 'vendor', 'business', ['business_id'], ['id'])
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(op.f('product_company_id_fkey'), 'product', 'business', ['company_id'], ['id'])
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.create_foreign_key(op.f('payment_business_id_fkey'), 'payment', 'business', ['business_id'], ['id'])
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.create_foreign_key(op.f('invoice_business_id_fkey'), 'invoice', 'business', ['business_id'], ['id'])
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.create_foreign_key(op.f('customer_business_id_fkey'), 'customer', 'business', ['business_id'], ['id'])
    op.drop_constraint(None, 'business', schema='public', type_='unique')
    op.drop_index(op.f('ix_public_business_slug'), table_name='business', schema='public')
    op.drop_column('business', 'db_name')
    op.drop_column('business', 'slug')
    # ### end Alembic commands ###
